/*Load Database*/

DROP TABLE IF EXISTS Player_data;

CREATE TABLE Player_data(
ID INT,
Player_ID INT PRIMARY KEY,
Player_Name TEXT,
Player_Age INT,
Photo TEXT,
Nationality TEXT,
Flag TEXT,
Overall INT,
Potential INT,
Club TEXT,
Club_Logo TEXT,
Player_Value VARCHAR(255),
Wage VARCHAR(255),
Special INT,
Preferred_Foot TEXT,
International_Reputation INT,
Weak_Foot INT,
Skill_Moves INT,
Work_Rate TEXT,
Body_Type TEXT,
Real_Face TEXT,
Player_Position TEXT,
Jersey_Number INT,
Joined VARCHAR(255),
Loaned_From TEXT,
Contract_Valid_Until VARCHAR(255),
Height VARCHAR(255),
Weight VARCHAR(255),
LS VARCHAR(255),
ST VARCHAR(255),
RS VARCHAR(255),
LW VARCHAR(255),
LF VARCHAR(255),
CF VARCHAR(255),
RF VARCHAR(255),
RW VARCHAR(255),
LAM VARCHAR(255),
CAM VARCHAR(255),
RAM VARCHAR(255),
LM VARCHAR(255),
LCM VARCHAR(255),
CM VARCHAR(255),
RCM VARCHAR(255),
RM VARCHAR(255),
LWB VARCHAR(255),
LDM VARCHAR(255),
CDM VARCHAR(255),
RDM VARCHAR(255),
RWB VARCHAR(255),
LB VARCHAR(255),
LCB VARCHAR(255),
CB VARCHAR(255),
RCB VARCHAR(255),
RB VARCHAR(255),
Crossing INT,
Finishing INT,
HeadingAccuracy INT,
ShortPassing INT,
Volleys INT,
Dribbling INT,
Curve INT,
FKAccuracy INT,
LongPassing INT,
BallControl INT,
Acceleration INT,
SprintSpeed INT,
Agility INT,
Reactions INT,
Balance INT,
ShotPower INT,
Jumping INT,
Stamina INT,
Strength INT,
LongShots INT,
Agression INT,
Interceptions INT,
Positioning INT,
Vision INT,
Penalties INT,
Composure INT,
Marking INT,
StandingTackle INT,
SlidingTackle INT,
GKDiving INT,
GKHandling INT,
GKKicking INT,
GKPositioning INT,
GKReflexes INT,
Release_Clause VARCHAR(255));

LOAD DATA INFILE 'Fifa19 data.csv' INTO TABLE Player_data
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"' 
    LINES TERMINATED BY '\n'
    IGNORE 1 LINES;





